version: "3"
services:
  sbx:
    container_name: sbx
    image: ashtr/devbox
    # command: |
    #   /bin/bash -c "(yarn install && ./node_modules/.bin/parcel --port ${APP_PORT} --hmr-port ${HMR_PORT} index.html)"
    entrypoint: ./scripts/sbx.entrypoint.sh
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${HMR_PORT}:${HMR_PORT}
    env_file:
      - ../environment/.sbx.default.env
      - ../environment/.sbx.${NODE_ENV}.env
      - ../environment/.sbx.env
    enironment:
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    volumes:
      - ../:${APP_DIR}
    working_dir: ${APP_DIR}
    networks: 
      - tsdev
networks: 
  tsdev:
