version: "3.2"
services:
  sbx:
    container_name: sbx
    image: ashtr/fe-devbox:carbon-alpine
    entrypoint: ./bin/sbx.entrypoint.sh
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${HMR_PORT}:${HMR_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    env_file:
      - ../environment/.sbx.default.env
      - ../environment/.sbx.${NODE_ENV}.env
      - ../environment/.sbx.env
    environment:
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    volumes:
      - ../:${APP_DIR}
    working_dir: ${APP_DIR}
    networks: 
      - tsdev
  sbx-test:
    depends_on: 
      - sbx
    container_name: sbx-test
    image: ashtr/fe-devbox:carbon-alpine
    command: >
      yarn test
    env_file:
      - ../environment/.sbx.default.env
      - ../environment/.sbx.qa.env
      - ../environment/.sbx.env
    environment:
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    volumes:
      - ../:${APP_DIR}:cached
    working_dir: ${APP_DIR}
    networks: 
      - tsdev
networks:
  tsdev: